name: my_own

on:
  push:
    branches:
      - my_own
  
  workflow_dispatch:

jobs:
  use-my-own-action:
    runs-on: ubuntu-latest
    steps:
      - name: helllo my world
        run: echo "my world !!! Hello!!!"



















